### ISSUE TITLE
GSS Distribution and data types

### ISSUE THREAD

**Issue by dt1729** [lassepe/GameInference.jl#1]
Hi Lasse,
I am trying to work on this repository and extend it to Ackermann dynamics in the future however; I wanted to know what data types are being used for GSS distribution the TO, TG, and TGA data types.

**Comment by lassepe** [comment]
I'm not sure which lines your questions refers to. Would you mind sharing links to the lines in the source code?

You can click on "copy permalink" in the menu to generate the link, e.g.:
![image](https://user-images.githubusercontent.com/10076790/163732773-2bc4abe4-6ae8-4153-801a-359cb2f78566.png)

**Comment by dt1729** [comment]
Here in the [inference.jl](https://github.com/lassepe/GameInference.jl/blob/e357a92d3fcfeb917c17ff9e43db3638f4aacf7e/src/inference.jl#L11) file

**Comment by lassepe** [comment]
You can find an example of how the GSS is constructed here (though I think you should never have to manually interact with it; but it's been quite a while that I've looked at this code):

https://github.com/lassepe/GameInference.jl/blob/f6e3500aa80cb86a129375c2e1d6dbb2195e4800/src/simulate.jl#L12

That is, `TO <: LQGames.SystemTrajectory`, `TG <: SizedVector{<: iLQGames.AffineStrategy}`, and `TGA <: iLQGames.GeneralGame`.

**Comment by lassepe** [comment]
I hope this answers your question. If not, feel free to re-open the issue.

**Comment by dt1729** [comment]
Hi Lasse, I'm trying to run the experiments however I'm running into this error:
`nested task error: MethodError: no method matching observation(::GameInference.GameSolutionModel{GameInference.CachingGSS{GameInference.GSSCache{50, SizedVector{50, GameInference.GSS{SystemTrajectory{100, 0.1, 12, 6, SizedVector{100, SVector{12, Float64}, Vector{SVector{12, Float64}}}, SizedVector{100, SVector{6, Float64}, Vector{SVector{6, Float64}}}}, SizedVector{100, iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}, Vector{iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}}}, GeneralGame{Int64, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, iLQGames.ProductSystem{0.1, 12, 6, 3, 12, Tuple{Unicycle4D{0.1}, Unicycle4D{0.1}, Unicycle4D{0.1}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}}, SVector{3, NPlayerUnicycleCost{iLQGames.QuadCost{SMatrix{2, 2, Float64, 4}}, Tuple{iLQGames.SoftConstr, iLQGames.SoftConstr}, iLQGames.QuadCost{SMatrix{4, 4, Float64, 16}}, Tuple{iLQGames.SoftConstr}, ProximityCost{SVector{3, Float64}, SVector{3, Float64}}, iLQGames.GoalCost{SVector{4, Float64}, SMatrix{4, 4, Float64, 16}}}}}}, Vector{GameInference.GSS{SystemTrajectory{100, 0.1, 12, 6, SizedVector{100, SVector{12, Float64}, Vector{SVector{12, Float64}}}, SizedVector{100, SVector{6, Float64}, Vector{SVector{6, Float64}}}}, SizedVector{100, iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}, Vector{iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}}}, GeneralGame{Int64, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, iLQGames.ProductSystem{0.1, 12, 6, 3, 12, Tuple{Unicycle4D{0.1}, Unicycle4D{0.1}, Unicycle4D{0.1}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}}, SVector{3, NPlayerUnicycleCost{iLQGames.QuadCost{SMatrix{2, 2, Float64, 4}}, Tuple{iLQGames.SoftConstr, iLQGames.SoftConstr}, iLQGames.QuadCost{SMatrix{4, 4, Float64, 16}}, Tuple{iLQGames.SoftConstr}, ProximityCost{SVector{3, Float64}, SVector{3, Float64}}, iLQGames.GoalCost{SVector{4, Float64}, SMatrix{4, 4, Float64, 16}}}}}}}}, SizedVector{50, Bool, BitVector}}}, Float64, SVector{12, Float64}, iLQSolver{iLQGames.LQGame{Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, iLQGames.LTVSystem{0.1, 12, 6, SizedVector{100, iLQGames.LinearSystem{0.1, 12, 6, SMatrix{12, 12, Float64, 144}, SMatrix{12, 6, Float64, 72}}, Vector{iLQGames.LinearSystem{0.1, 12, 6, SMatrix{12, 12, Float64, 144}, SMatrix{12, 6, Float64, 72}}}}}, SizedVector{100, SVector{3, iLQGames.QuadraticPlayerCost{12, 6, SVector{12, Float64}, SMatrix{12, 12, Float64, 144}, SVector{6, Float64}, SMatrix{6, 6, Float64, 36}}}, Vector{SVector{3, iLQGames.QuadraticPlayerCost{12, 6, SVector{12, Float64}, SMatrix{12, 12, Float64, 144}, SVector{6, Float64}, SMatrix{6, 6, Float64, 36}}}}}}, SystemTrajectory{100, 0.1, 12, 6, SizedVector{100, SVector{12, Float64}, Vector{SVector{12, Float64}}}, SizedVector{100, SVector{6, Float64}, Vector{SVector{6, Float64}}}}, iLQGames.QuadCache{12, 6, MVector{12, Float64}, MMatrix{12, 12, Float64, 144}, MVector{6, Float64}, MMatrix{6, 6, Float64, 36}}}, typeof(identity)}, ::GameInference.CachingGSS{GameInference.GSSCache{50, SizedVector{50, GameInference.GSS{SystemTrajectory{100, 0.1, 12, 6, SizedVector{100, SVector{12, Float64}, Vector{SVector{12, Float64}}}, SizedVector{100, SVector{6, Float64}, Vector{SVector{6, Float64}}}}, SizedVector{100, iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}, Vector{iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}}}, GeneralGame{Int64, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, iLQGames.ProductSystem{0.1, 12, 6, 3, 12, Tuple{Unicycle4D{0.1}, Unicycle4D{0.1}, Unicycle4D{0.1}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}}, SVector{3, NPlayerUnicycleCost{iLQGames.QuadCost{SMatrix{2, 2, Float64, 4}}, Tuple{iLQGames.SoftConstr, iLQGames.SoftConstr}, iLQGames.QuadCost{SMatrix{4, 4, Float64, 16}}, Tuple{iLQGames.SoftConstr}, ProximityCost{SVector{3, Float64}, SVector{3, Float64}}, iLQGames.GoalCost{SVector{4, Float64}, SMatrix{4, 4, Float64, 16}}}}}}, Vector{GameInference.GSS{SystemTrajectory{100, 0.1, 12, 6, SizedVector{100, SVector{12, Float64}, Vector{SVector{12, Float64}}}, SizedVector{100, SVector{6, Float64}, Vector{SVector{6, Float64}}}}, SizedVector{100, iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}, Vector{iLQGames.AffineStrategy{12, 6, SMatrix{6, 12, Float64, 72}, SVector{6, Float64}}}}, GeneralGame{Int64, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, iLQGames.ProductSystem{0.1, 12, 6, 3, 12, Tuple{Unicycle4D{0.1}, Unicycle4D{0.1}, Unicycle4D{0.1}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}, Tuple{SVector{4, Int64}, SVector{4, Int64}, SVector{4, Int64}}, Tuple{SVector{2, Int64}, SVector{2, Int64}, SVector{2, Int64}}}, SVector{3, NPlayerUnicycleCost{iLQGames.QuadCost{SMatrix{2, 2, Float64, 4}}, Tuple{iLQGames.SoftConstr, iLQGames.SoftConstr}, iLQGames.QuadCost{SMatrix{4, 4, Float64, 16}}, Tuple{iLQGames.SoftConstr}, ProximityCost{SVector{3, Float64}, SVector{3, Float64}}, iLQGames.GoalCost{SVector{4, Float64}, SMatrix{4, 4, Float64, 16}}}}}}}}, SizedVector{50, Bool, BitVector}}})
    Closest candidates are:
      observation(::POMDPs.POMDP, ::Any, ::Any) at ~/.julia/packages/POMDPs/85BFM/src/pomdp.jl:61
      observation(::POMDPs.POMDP, ::Any, ::Any, ::Any) at ~/.julia/packages/POMDPs/85BFM/src/pomdp.jl:64
      observation(::POMDPModelTools.FullyObservablePOMDP, ::Any, ::Any) at ~/.julia/packages/POMDPModelTools/QuTqm/src/fully_observable_pomdp.jl:22
`

This is during the run simulation call by solve_distribution for any of the cases(uncertain-equilibria, uncertain proximity, uncertain goal). Seems like a library version(or maybe type conversion(GSS to some other distribution)) issue. Let me know, thanks.

**Comment by lassepe** [comment]
Thanks for sharing the error message. Is that in the original version of the code or you modified version? It would be good if you could send a minimal set of instructions to reproduce this error. If you send me those, I can help to debug.

**Comment by dt1729** [comment]
Hi Lasse this is a fresh clone of the repository. I tried to run the file main.jl in the experiments folder by using run_ungoal(), run_unprox(), run_uneq().

**Comment by lassepe** [comment]
I am unable to reproduce the error but I am also not able to instantiate the project with a recent Julia version. I suspect that this is due to a change in the Julia version or iLQGames which has changed the datatype and thereby the dispatch route. In fact, you must have made some modifications to this repo: it only runs with julia 1.4 and older and you have to have the correct Manifest. How did you resolve this?

That said, I have now checked the `Manifest.toml` to record the exact versions of dependencies which are needed to reproduce the experiments. I also added a note to the README that states the last julia version that this was tested with. With that, I am able to run all experiments. I unfortunately have no capacity to port this repo to a more recent set of dependencies. However, I'm happy to merge a PR on this if anyone is interested to contribute.

**Comment by dt1729** [comment]
Hi again, I cloned this repository fresh to run the experiments and still had these problems. I did not change Manifest.toml but I had during my first install changed version symbol from `=` to `>=` Project.toml, to install all the dependencies it is possible new versions of these repositories are causing issues.

**Comment by lassepe** [comment]
Yes, if you drop the version bounds on dependencies then there is no guarantee that things still work.
